; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{48BD3BAE-7024-4749-B7DD-F6F7474D65BC}
AppName=CS-Py
AppVersion=0.3
;AppVerName=CS-Py 0.3
AppPublisher=Parkkeo1
AppPublisherURL=https://github.com/Parkkeo1/CS-Py
AppSupportURL=https://github.com/Parkkeo1/CS-Py
AppUpdatesURL=https://github.com/Parkkeo1/CS-Py
DefaultDirName={pf}\CS-Py
DisableProgramGroupPage=yes
InfoBeforeFile=C:\Users\Isaac\CS-Py\build\exe.win-amd64-3.6\README.txt
InfoAfterFile=C:\Users\Isaac\CS-Py\build\exe.win-amd64-3.6\README.txt
OutputDir=C:\Users\Isaac\CS-Py\inno installers
OutputBaseFilename=install_cspy
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\Isaac\CS-Py\build\exe.win-amd64-3.6\CS-Py.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Isaac\CS-Py\build\exe.win-amd64-3.6\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\CS-Py"; Filename: "{app}\CS-Py.exe"
Name: "{commondesktop}\CS-Py"; Filename: "{app}\CS-Py.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\CS-Py"; Filename: "{app}\CS-Py.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\CS-Py.exe"; Description: "{cm:LaunchProgram,CS-Py}"; Flags: nowait postinstall skipifsilent

